export const NOTIFICATION_MSG = {
  billigIdRequired: 'Please add a Billing ID',
  shippingIdRequired: 'Please select a shipping id for all Billing Ids',
  settingsRequired: 'Please enable one Privieges Access',
  basicInfoRequired: 'Please enter all basic information with valid data',
  passwordNotMatch: 'Passwords should match',
  dashboardMenuNotificationMSG: 'This feature is not available for the Admin users',
  yearNotValid: 'Please enter a valid Year',
  searchFormNotValid: 'Please enter a value in any Search Field or Clear Filter',
  mobileNoValidation: 'Please enter a valid Mobile Number',
  minOneBillingId: 'Atleast one billing id should be selected',
  passwordNotMatched: 'New and confirm password is not matched',
  samePassword: 'Old and new password should not be the same',
  mandatoryMsg: 'Please enter all mandatory fields with valid data',
  kpiReportRequired: 'Please selecte a KPI report before filtering',
  dateValidation: 'To date should be greater than or equal to from date',
  date2Validation: 'Please select maximum of 1 year gaps between from date and to date',
  filterValidation: 'Please enter a any value to filter',
  fileDownloadMsg: 'File downloaded successfully',
  emailValidation: 'Please enter valid emails without white spaces & trailing commas',
  WORequired: 'Please select a Work Order type',
  EmergencyServiceMsg: 'For immediate service after our normal business hours of 7am-5pm, please call 856-541-1290 to place a service request.',
  InvalidFileName: 'Invalid file name',
  InvalidFileType: 'Invalid file type',
  InvalidFileSize: 'File size should be less than 10MB',
  InvalidPasswordPattern: 'Password Pattern Not Matching',
  noReportId: 'Please select a Report Type',
  woPdfValidationMSG: 'WO PDF is not available for the current WO status',
  sessionExpired: 'Your session has expired. Please login again',
  INVALID_CREDENTIAL: 'Please enter valid credential',
  apiError: 'Something went wrong. Please try again',
  equipmentDetailsValidation: ' The selected equipment is not assigned to your shipTo address',
  inValidDateFormat: 'Please enter a valid date in format MM/DD/YYYY',
  woPdfInvoiceValidationMSG: 'WO PDF is not available',
  clamTypeAdded:"Claim Type Added Successfully"
};
