import { environment } from 'src/environments/environment';

const { baseUrl } = environment;
// const { woPdfBaseUrl } = environment;
export const URLS = Object.freeze({
  loginUrl: `${baseUrl}account/login`,
  resetPasswordUrl: `${baseUrl}account/resetPassword`,
  getWorkOrderListUrl: `${baseUrl}workorders/getWorkorderList`,
  getPMWorkOrderListUrl: `${baseUrl}workorders/getpmWorkorderList`,
  getInvoiceListUrl: `${baseUrl}invoice/getInvoiceList`,
  getExecutiveSummaryUrl: `${baseUrl}invoice/getExecutiveSummary`,
  getMonthlyServiceComparisonUrl:`${baseUrl}report/monthlyServiceComparison`,
  getBillingId: `${baseUrl}admin/getAllBillingId`,
  getEquipmentListMetadataUrl: `${baseUrl}metadata/equipmentSearchList`,
  getEquipmentDetailsUrl: `${baseUrl}equipment/details`,
  adminActiveSettingsUrl: `${baseUrl}metadata/activeSettings`,
  addUserUrl: `${baseUrl}admin/createUser`,
  getWoStatusGraphUrl: `${baseUrl}workorders/getwostatusgraph`,
  getWoStatusMetadataUrl: `${baseUrl}metadata/workOrderStatus`,
  equipmentListUrl: `${baseUrl}equipment/list`,
  updateUserPrivilageAccessUrl: `${baseUrl}user/updateUserPrevAccess`,
  locationUrl: `${baseUrl}metadata/locationList`,
  kpiReportMetaData: `${baseUrl}metadata/kpiReportList`,
  departmentUrl: `${baseUrl}metadata/departmentList`,
  kpiReportUrl: `${baseUrl}kpi/getReport`,
  kpiReportDownload: `${baseUrl}kpi/downloadReport`,
  equipmentListDownload: `${baseUrl}equipment/downloadList`,
  invoiceListDownload: `${baseUrl}invoice/downloadList`,
  userLsitingUrl: `${baseUrl}admin/listUser`,
  // woPDFUrl: `${woPdfBaseUrl}Files/RV/WorkOrders/`,
  editUserDetails: `${baseUrl}admin/editUserDetails`,
  editUserUrl: `${baseUrl}admin/editUserDetailsSave`,
  createServiceRequestUrl: `${baseUrl}request/serviceRequest`,
  createPMRequestUrl: `${baseUrl}request/pmRequest`,
  userStatusUpdateUrl: `${baseUrl}admin/userStatusUpdate`,
  resetPassword: `${baseUrl}admin/sendNewPassword`,
  adminSettingsUrl: `${baseUrl}admin/getAllAdminSettings`,
  updateAdminSettings: `${baseUrl}admin/adminSettingsUpdate`,
  serviceReports: `${baseUrl}metadata/serviceReportList`,
  serviceReportDownload: `${baseUrl}service/downloadServiceDetails`,
  emergencyServiceMetadata: `${baseUrl}metadata/emergencyService`,
  invoicePdfDonwload: `${baseUrl}invoice/downloadInvoice`,
  forgotPassword: `${baseUrl}account/forgotPassword`,
  submitForgotPasswordOtp: `${baseUrl}account/forgotPasswordSave`,
  logout: `${baseUrl}account/logout`,
  customerListPdfDonwload: `${baseUrl}admin/downloadListUser`,
  refreshToken: `${baseUrl}account/getRefreshToken`,
  getCurrentMHECost: `${baseUrl}report/currentMHECost`,
  getAvoidableSpend: `${baseUrl}report/avoidableSpend`,
  fleetComposition:`${baseUrl}report/fleetComposition`,
  monthlyRentalComparison:`${baseUrl}report/monthlyRentalComparison`,
  monthlyServiceComparison:`${baseUrl}report/monthlyServiceComparison`,
  spendByClaimType:`${baseUrl}report/spendByClaimType`,
  top10AssetTotals:`${baseUrl}report/top10AssetTotals`,
  getTopAssetList:`${baseUrl}report/topAssetList`,
  getFleetAssetSummary:`${baseUrl}report/fleetAssetSummary`,
  getClaimTypeList:`${baseUrl}workorders/claimTypeWOList`,
  getClaimTypeMetadataUrl: `${baseUrl}metadata/getClaimType`,
  saveWOClaimType:`${baseUrl}workorders/saveWOClaimType`,
  fleetAssetSummaryReportDownload:`${baseUrl}report/downloadFleetAssetSummaryList`
});
